#!/usr/bin/python3
##############################################
#
# This is open source software licensed under the Apache License 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
##############################################

from plantgw.plantgw import PlantGateway, SensorConfig
import sys


def main():
    pg = None
    try:
        pg = PlantGateway()
        pg.publish_health('running')
        failed_sensors = pg.process_all()
        # only count the sensors that are NOT fail silent
        num_failed = len([s for s in failed_sensors if not s.fail_silent])
        if len(failed_sensors) > 0:
            print('Could not get data from {} sensor(s): {}.'.format(
                len(failed_sensors),
                SensorConfig.get_name_string(failed_sensors)))
        status = 'error' if num_failed > 0 else 'ok'
        pg.publish_health(status, failed_sensors)
        sys.exit(num_failed)
    except Exception as exception:
        if pg is not None:
            try:
                pg.publish_health('error', message=str(exception))
            except Exception:
                pass
        raise
    finally:
        if pg is not None:
            pg.stop_client()


if __name__ == '__main__':
    main()
